### PR TITLE
recognize 'Sort-Object', 'Sleep'

### PR DESCRIPTION
**Pull request by martinlindhe**

### CODE REVIEW

**Comment by jugglingnutcase** [comment]
Hi @martinlindhe! Thanks for the PR 😄 

It's better to submit language issues to the language repository this tool is basing its grammar on: https://github.com/PowerShell/EditorSyntax... **but it's my fault for not having that clearly stated anywhere in this repository!** I'm sorry about that.

It's also my fault that the editor language is behind their grammar, it's a fairly recent development and I haven't kept up with it so far.

I'll take a look at their grammar and see if I can apply it here and then bump the package. If this is still an issue after that, we'll work together on forwarding it to their repository.

Again, I'm sorry for the lack of information here! I'll update the repo and see if we can get this resolved.

**Comment by martinlindhe** [comment]
Sounds good, thanks for the update!

**Comment by jugglingnutcase** [comment]
I've just bumped the package and it looks like `Sort-Object` and `Sleep` get highlighted correctly. If I'm missing something though, please open an issue or PR against the https://github.com/PowerShell/EditorSyntax repo if you find any problems with them.

Thanks again 😄

**Comment by martinlindhe** [comment]
Looks good, thanks!

**Pull request closed without merging**
