### PR TITLE
Move to PowerShell/EditorSyntax as the backing grammar

### PR DESCRIPTION
**Pull request by jugglingnutcase**
This moves this library's backing grammar from the old SublimeText/PowerShell repository to the Microsoft-backed PowerShell/EditorSyntax repository.

### CODE REVIEW

**Comment by daviwil** [comment]
Wow!  I didn't know you had made the transition :)  We had to back out of using it in VS Code for a little while because users had trouble with certain aspects of the syntax highlighting.  

It's good that you're passing along the issues people are finding, hopefully we'll be able to get them fixed in the near future.  @vors is currently working on some test automation that should help us flush out all the remaining issues.

**Comment by daviwil** [comment]
Looks like you had to remove some of your existing tests, were things too broken to get them to pass?

**Comment by jugglingnutcase** [comment]
Hm, now that you say it, I think it was premature to do both of those
things. The users end up paying in these regressions. 😢

I guess I assumed this grammar's highlighting was at least as good as the
old SublimeText one and users wouldn't hurt too much from the transition.

I didn't want to duplicate functionality so I figured I'd leave testing the
grammars to this repository as well.

I'll take some time and consider rolling back on this, maybe I got a little
too enthusiastic with the transition!

**Comment by daviwil** [comment]
Yeah, we thought it was too until people started trying it and hitting major issues.  I apologize for not making it more clear the state of things after we figured that out.  Hopefully within the next couple of months the new grammar will be all fixed up and ready to go again.

Makes sense to let the main repo do the grammar testing, but it'd be interesting to know what cases you specifically thought were interesting so we can cover them too!

**Comment by vors** [comment]
> I guess I assumed this grammar's highlighting was at least as good as the
old SublimeText one and users wouldn't hurt too much from the transition.

@jugglingnutcase we are so sorry about this. We didn't communicate the status of this work clearly.
I was busy with https://github.com/PowerShell/PowerShell in the past few months and let it slip a little bit. People noticed regressions in VSCode https://github.com/PowerShell/EditorSyntax/issues/16

I'd recomend to rever to the old Submile grammar until the first release from https://github.com/PowerShell/EditorSyntax
Particularly, I'm hoping to finish the testing framework https://github.com/PowerShell/EditorSyntax/issues/2 so we can start with a solid foundation to catch regressions.

At the meantime, would you like to become a maintainer (with write access) for the https://github.com/PowerShell/EditorSyntax ?
This way, we will have all **package maintainers** represented as maintainers in EditorSyntax:

* @jugglingnutcase for Atom
* @vors for SublimeText
* @daviwil for VSCode

**Pull request merged**
